version: '3'
services:
  gobanners:
    container_name: "gobanners"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    networks:
      - mynet
    volumes:
      - ./.env:/gobanners/.env
    restart: unless-stopped

  postgres:
    image: "postgres:latest"
    hostname: "postgres"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DBPASSWORD}"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
